version: "3.9"

services:
  init:
    build:
      context: .
    command: init
    environment:
      MEILI_HOST_URL: "${MEILI_HOST_URL:-http://meilisearch:7700}"
      MEILI_INDEX_UID: "${MEILI_INDEX_UID:-crates}"
      MEILI_API_KEY: "${MEILI_MASTER_KEY}"
      RUST_LOG: "${RUST_LOG-search_crates_pm=debug,info}"
    restart: no

  update:
    build:
      context: .
    environment:
      MEILI_HOST_URL: "${MEILI_HOST_URL:-http://meilisearch:7700}"
      MEILI_INDEX_UID: "${MEILI_INDEX_UID:-crates}"
      MEILI_API_KEY: "${MEILI_MASTER_KEY}"
      RUST_LOG: "${RUST_LOG-search_crates_pm=debug,info}"
    restart: unless-stopped

  meilisearch:
    volumes:
      - integrate_meilisearch-data:/data.ms
    environment:
      MEILI_ENVIRONMENT: "production"
      MEILI_MASTER_KEY: "${MEILI_MASTER_KEY}"

volumes:
  integrate_meilisearch-data:
