version: "3.9"

services:
  dozzle:
    image: docker.io/amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - 9999:8080

  meilisearch:
    depends_on: [dozzle]
    volumes:
        - dev_meilisearch-data:/data.ms

volumes:
  dev_meilisearch-data:
