[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
main_project_member = "scyllax"
default_to_workspace = false

[tasks.setup]
script = '''
    echo # installing git hooks
    pre-commit --version || pip install pre-commit
    pre-commit install || echo "failed to install git hooks!" 1>&2
'''

[tasks.full-init]
command = "cargo"
args = ["run", "--release", "--bin", "full_init"]

[tasks.clone-index]
command = "git"
args = ["clone", "--progress", "--depth=1", "git@github.com/rust-lang/crates.io-index.git"]

[tasks.lint]
install_crate = "clippy"
command = "cargo"
args = [
    "clippy",
    "--tests",
    "--examples",
    "--all-targets",
    "--all-features",
    "--workspace",
]

[tasks.lint-ci]
install_crate = "clippy"
command = "cargo"
args = [
    "clippy",
    "--tests",
    "--examples",
    "--all-targets",
    "--all-features",
    "--workspace",
    "--",
    "-D",
    "warnings",
]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]

[tasks.fmt]
alias = "format"

[tasks.format-ci]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]
