name: Website

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: web

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: web

      - name: Setup Volta
        uses: volta-cli/action@v3

      - name: Install dependencies
        uses: trufflehq/truffle-packages/actions/yarn@main
        with:
          working-directory: web

      - name: Build website
        env:
          VERCEL_URL: ${{ vars.WEBSITE_URL }}
        run: yarn build

      - name: Bundle
        run: cd out && tar -czvf ../web-$GITHUB_SHA.tar.gz .

      - name: Releasing assets
        uses: actions/upload-artifact@v3
        with:
          path: web*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
